### ISSUE TITLE
02.02.2022 сломалась автовыгрузка

### ISSUE THREAD

**Issue by EAnsy** [yegorov-p/python-zapret-info#6]
02.02.2022 вероятно, после обновления сервиса (добавили социально значимые ресурсы) сломалась автоматическая выгрузка реестра. Запрос и ЭЦП свежие, в ручном режиме загружают нормально. А скрипт исправно получает одноразовые коды, но не получает файл с дампом. В логе ошибки:
```
Traceback (most recent call last):
  File "./zapret_checker.py", line 164, in <module>
    main()
  File "./zapret_checker.py", line 124, in main
    request['operatorName'].decode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'decode'
```
И вот такое по кругу:
```
2022-02-06 19:06:06,250  Starting script.
2022-02-06 19:06:06,251  Check if dump.xml already exists.
2022-02-06 19:06:06,251  dump.xml does not exist
2022-02-06 19:06:06,251  Check if dump.xml has updates since last sync.
2022-02-06 19:06:06,363  Current versions: webservice: 3.2, dump: 2.4, doc: 4.12
2022-02-06 19:06:06,363  New dump is available.
2022-02-06 19:06:06,364  Sending request.
2022-02-06 19:06:06,533  Checking request status.
2022-02-06 19:06:06,533  Got code 6565ca6f6ff93d733134ae010dd001f1
```

**Comment by yegorov-p** [comment]
У меня, к сожалению, давно уже не доступа к ЭЦП, поэтому мне подебажить не на чем (

**Comment by EAnsy** [comment]
Ок, ну тогда я немного подебажил ;)
Хотя я совсем не питонщик и не знаток всяких мудрёных SOAP API, но вот это закомментарил:
```
#                        logger.info('Got a dump ver. %s for the %s (INN %s)',
#                                    request['dumpFormatVersion'],
#                                    request['operatorName'].decode('utf-8'),
#                                    request['inn'])
```
и оно успешно провалилось дальше и даже скачало дамп :)
На патч не катит, но workaround -- вполне.
А за скрипт -- СПАСИБО!

**Comment by segalws** [comment]
Добавил пул реквест на починку этой ошибки + добавил выгрузку социально значимых сайтов https://github.com/yegorov-p/python-zapret-info/pull/7

**Comment by segalws** [comment]
> 

Это из реестра почему то не прилетает inn и operatorName
