### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Diamond-ik** [yegorov-p/python-zapret-info#9]
Traceback (most recent call last):
  File "zapret_checker.py", line 190, in <module>
    main()
  File "zapret_checker.py", line 102, in main
    last_dump = session.getLastDumpDateEx()
AttributeError: ZapretInfo instance has no attribute 'getLastDumpDateEx'

если изменить на 'getLastDumpDate, то выдает:

Traceback (most recent call last):
  File "zapret_checker.py", line 190, in <module>
    main()
  File "zapret_checker.py", line 104, in main
    last_dump.webServiceVersion,
AttributeError: 'long' object has no attribute 'webServiceVersion'
'

**Comment by Diamond-ik** [comment]
разобрался, не обновился второй файл. теперь все гуд, спасибо
